import { MigrationInterface, QueryRunner } from "typeorm";

export class ConvertToSnakeCase1770157937525 implements MigrationInterface {
    name = 'ConvertToSnakeCase1770157937525'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "group-members" DROP CONSTRAINT "FK_41baa2a552166436d8e2a037a7a"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP CONSTRAINT "FK_1f0b355f60e019e32c1404a837b"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_7a539a1aa08caa4961ae168c700"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_348ceef2165d4fcb592a77acb41"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP CONSTRAINT "FK_9554aa6b8f2c9abc2613f7fcd9e"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP CONSTRAINT "FK_de264c268b61ea74b74066eb4d6"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_074087a27dd062b96697e84beac"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP CONSTRAINT "FK_2a2f49793779d4d8aae1db00320"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP CONSTRAINT "FK_5d03c24cf83a025d6c14c20fdb1"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP CONSTRAINT "FK_b75d86ea0c798f196ac3df0d161"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_5fa1e0b256a41ed68d40521fabb"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_4161468060bc6443aa754479667"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP CONSTRAINT "FK_dff93f57c684c920ca09175d1ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d1a1130c8184b69878e356614"`);
        await queryRunner.query(`ALTER TABLE "socials" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "socials" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "artistId"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "REL_7a539a1aa08caa4961ae168c70"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "socialId"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "imgPath"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "postedAt"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "youtubeUrls"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "songId"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "artistId"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "REL_074087a27dd062b96697e84bea"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "socialId"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "imgPath"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "songId"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "artistId"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "UQ_b443618a8149644123d48eceed4"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "refreshToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "dateStart"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "dateEnd"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "imgPaths"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "venueId"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "festivalId"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "countryCode"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "cityId"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "imgPath"`);
        await queryRunner.query(`ALTER TABLE "socials" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socials" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "artist_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "img_path" character varying`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "social_id" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "UQ_3d6003dcc0a38505a670ea1a6e3" UNIQUE ("social_id")`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "youtube_urls" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "posted_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "song_id" uuid`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "artist_id" uuid`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "img_path" character varying`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "social_id" uuid`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "UQ_05276346e6758d9a02108e0f1cb" UNIQUE ("social_id")`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "song_id" uuid`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "artist_id" uuid`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "refresh_token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "UQ_c862499023be8feec98129d4e96" UNIQUE ("refresh_token")`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "date_start" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "date_end" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "img_paths" character varying array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "venue_id" uuid`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "festival_id" uuid`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "country_code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "img_path" character varying`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "city_id" uuid`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0148b2dd7b07ee1a737084b8d2" ON "confirmations" ("user_id", "type") `);
        await queryRunner.query(`ALTER TABLE "group-members" ADD CONSTRAINT "FK_e76dbd6fc64d0d8d5e5c21597ef" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD CONSTRAINT "FK_20a0607f9e3bbe63594e98ea69a" FOREIGN KEY ("artist_id") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_3d6003dcc0a38505a670ea1a6e3" FOREIGN KEY ("social_id") REFERENCES "socials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_19fedfa063687b33ffefd903d05" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD CONSTRAINT "FK_6d8ef8482a707ecce91e196c3ff" FOREIGN KEY ("song_id") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD CONSTRAINT "FK_eae4450ea21145b63db07666388" FOREIGN KEY ("artist_id") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_05276346e6758d9a02108e0f1cb" FOREIGN KEY ("social_id") REFERENCES "socials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD CONSTRAINT "FK_32646b0e5ddfcd51705a4310493" FOREIGN KEY ("song_id") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD CONSTRAINT "FK_94d85913ce11490b9bbf490a0b4" FOREIGN KEY ("artist_id") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD CONSTRAINT "FK_1064a35689548a606231b93db2c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_d9ffdac680156b5df83652f59b2" FOREIGN KEY ("venue_id") REFERENCES "venues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_86092331a2fb2b0d787fb317f50" FOREIGN KEY ("festival_id") REFERENCES "festivals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "venues" ADD CONSTRAINT "FK_c2ab6dcc752b5c95b2baefb41c8" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "venues" DROP CONSTRAINT "FK_c2ab6dcc752b5c95b2baefb41c8"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_86092331a2fb2b0d787fb317f50"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP CONSTRAINT "FK_d9ffdac680156b5df83652f59b2"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP CONSTRAINT "FK_1064a35689548a606231b93db2c"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP CONSTRAINT "FK_94d85913ce11490b9bbf490a0b4"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP CONSTRAINT "FK_32646b0e5ddfcd51705a4310493"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_05276346e6758d9a02108e0f1cb"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP CONSTRAINT "FK_eae4450ea21145b63db07666388"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP CONSTRAINT "FK_6d8ef8482a707ecce91e196c3ff"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_19fedfa063687b33ffefd903d05"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_3d6003dcc0a38505a670ea1a6e3"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP CONSTRAINT "FK_20a0607f9e3bbe63594e98ea69a"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP CONSTRAINT "FK_e76dbd6fc64d0d8d5e5c21597ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0148b2dd7b07ee1a737084b8d2"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "img_path"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "country_code"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "festival_id"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "venue_id"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "shows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "img_paths"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "date_end"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "date_start"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "festivals" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "UQ_c862499023be8feec98129d4e96"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "confirmations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "artist_id"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "song_id"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "song-performers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "UQ_05276346e6758d9a02108e0f1cb"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "social_id"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "img_path"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "artist_id"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "song_id"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "song-writers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "posted_at"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "youtube_urls"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "UQ_3d6003dcc0a38505a670ea1a6e3"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "social_id"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "img_path"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "artist_id"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "group-members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "socials" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "socials" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "imgPath" character varying`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "cityId" uuid`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "venues" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "countryCode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "festivalId" uuid`);
        await queryRunner.query(`ALTER TABLE "shows" ADD "venueId" uuid`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "imgPaths" character varying array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "dateEnd" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "dateStart" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "festivals" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "refreshToken" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "UQ_b443618a8149644123d48eceed4" UNIQUE ("refreshToken")`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "artistId" uuid`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "songId" uuid`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "imgPath" character varying`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "socialId" uuid`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "REL_074087a27dd062b96697e84bea" UNIQUE ("socialId")`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "artists" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "artistId" uuid`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "songId" uuid`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "youtubeUrls" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "groupId" uuid`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "postedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "songs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "imgPath" character varying`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "socialId" uuid`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "REL_7a539a1aa08caa4961ae168c70" UNIQUE ("socialId")`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "artistId" uuid`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "groupId" uuid`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socials" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socials" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7d1a1130c8184b69878e356614" ON "confirmations" ("type", "userId") `);
        await queryRunner.query(`ALTER TABLE "venues" ADD CONSTRAINT "FK_dff93f57c684c920ca09175d1ad" FOREIGN KEY ("cityId") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_4161468060bc6443aa754479667" FOREIGN KEY ("festivalId") REFERENCES "festivals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shows" ADD CONSTRAINT "FK_5fa1e0b256a41ed68d40521fabb" FOREIGN KEY ("venueId") REFERENCES "venues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "confirmations" ADD CONSTRAINT "FK_b75d86ea0c798f196ac3df0d161" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD CONSTRAINT "FK_5d03c24cf83a025d6c14c20fdb1" FOREIGN KEY ("artistId") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-performers" ADD CONSTRAINT "FK_2a2f49793779d4d8aae1db00320" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_074087a27dd062b96697e84beac" FOREIGN KEY ("socialId") REFERENCES "socials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD CONSTRAINT "FK_de264c268b61ea74b74066eb4d6" FOREIGN KEY ("artistId") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song-writers" ADD CONSTRAINT "FK_9554aa6b8f2c9abc2613f7fcd9e" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_348ceef2165d4fcb592a77acb41" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_7a539a1aa08caa4961ae168c700" FOREIGN KEY ("socialId") REFERENCES "socials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD CONSTRAINT "FK_1f0b355f60e019e32c1404a837b" FOREIGN KEY ("artistId") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group-members" ADD CONSTRAINT "FK_41baa2a552166436d8e2a037a7a" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
