import { Provider } from '$components/organisms/provider'
import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head></head>
      <Provider>
        <body
          className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
        >
          {children}
          <Toaster richColors position="bottom-right" />
        </body>
      </Provider>
    </html>
  )
}

export const rootLayoutMetadata: Metadata = {
  title: 'New Blood',
  description: 'Welcome to New Blood',
  icons: [{ url: '/images/globe.png', sizes: 'any' }],
}
